### ISSUE TITLE
Add options to restrict download to particular connection types

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/background-fetch#1]
I'm in two minds about this.

We could add these options to [background sync](https://wicg.github.io/BackgroundSync/spec/), then developers could trigger the background-cache from the sync event. This seems like a nice lower-level way of doing it.

Alternatively, we could add the feature directly to background-cache. This would be higher-level, but would allow the OS to pause the download if the connection changes.

**Comment by jkarlin** [comment]
I don't think it makes sense to add add the options to background sync just to support this API. We'd need to find other use cases first.

We don't need to add the options to the public API at all, and could let the user change the setting via a prompt when a large upload/download is requested.

**Comment by jakearchibald** [comment]
> the setting via a prompt when a large upload/download is requested

I don't think the download will always be triggered by a user-interaction. See the podcasting example https://github.com/jakearchibald/background-cache#downloading-a-podcast-in-reaction-to-a-push-message - I don't think this would work if the user has to accept the download.

**Comment by StefanGussner** [comment]
Letting the OS handle the pausing on network change seems like a good idea. Maybe add a setting in the browser to let the user decide which networks to use for this kind of sync.
This way the user wouldn't have to change this behavior for each website (if the option would be provided anyway).

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/background-fetch/commit/52bf7437807d2b540697d35f7f5002c09543315d
