### ISSUE TITLE
Remove bgCacheReg.done

### ISSUE THREAD

**Issue by jenharkness** [jakearchibald/background-fetch#10]
The API is intended for Service Workers and most of the time will expect that the download/upload completes a significant time after it's started. In that case, most consumers will be implementing event listeners to deal with success/failure. 

If event listeners are going to be the expected use case for notification on status, I'd suggest you remove the "done" promise just to keep the API clean.

**Comment by jakearchibald** [comment]
I wanted `.done` for page-based code, but you can replicate this using SW and `postMessage`.

I'll remove this, but we should look into ways of exposing progress so pages can show UI. Happy for that to be v2.

**Comment by jakearchibald** [comment]
Done, although I ended up recreating it in most of my examples, see `backgroundFetchDone` https://github.com/jakearchibald/background-fetch/blob/master/README.md
