### ISSUE TITLE
Deferred background upload of large files

### ISSUE THREAD

**Issue by FLamparski** [jakearchibald/background-fetch#5]
Hi,

I currently work for Kinderly and am scoping out a way to rewrite our current Flash/Air mobile app as a progressive web application. One of the key requirements is the ability to schedule fire-and-forget uploads of large files (photos and videos in addition to other data) when the user is offline, for automatic assumption and resumption when the user returns online. The use case is as follows:

Picture a nursery with a large garden, with one crappy BT Hub from 5 years ago. The manager there bought a bunch of cheap tablets¹ with just WiFi on them and told the staff that they need to use these to take EYFS observations and attach photos and videos to them. Now, in the far end of the garden, the WiFi is nonexistent so the app absolutely must work offline - so far that's not too much of a problem as service workers are already here. Then the staff return the devices to the office, where it can connect to WiFi again. What should happen at this point is that background sync should be initiated, and all those observations with media attached should start being uploaded to the server.

My question is, how much of this use case is covered by the current service worker spec as well as this proposal? On first reading of [this example](https://github.com/jakearchibald/background-cache#uploading-a-video-in-the-background) it seems like it may actually be quite difficult to pull off, requiring a request to be fired immediately and then put on hold by the cache. In my scenario, I'd like to be able to store all the media in say IndexedDB, and initiate uploads in response to some event that informs the service worker that it has network again (unsure if I can listen to online/offline events in a service worker, probably not).

¹ For now I'm assuming Android tablets which can run latest Chrome; I have no illusions that a shim Cordova app for iOS won't be necessary

**Comment by jakearchibald** [comment]
https://developers.google.com/web/updates/2015/12/background-sync?hl=en solved this already for small uploads & downlaods. But this spec will solve it for larger ones.

**Comment by Westbrook** [comment]
@jakearchibald would you have any preliminary thoughts as to around the file size and/or transfer time that would mark the boundary between background-sync and background-cache? If that boundary wasn't a fixed size, the browser time out in the description lightly implies that, would you see a world where we err on he side of background-cache or possibly a somewhat fluid switch by which the browser could move activities between the two as size and connectivity, etc warranted?

**Comment by jakearchibald** [comment]
@Westbrook 

> would you have any preliminary thoughts as to around the file size and/or transfer time that would mark the boundary between background-sync and background-cache?

I think it's more: If an OS notification showing the progress of the upload/download feels like overkill, you're probably better off with background sync.
