### ISSUE TITLE
Don't use sequence for an attribute

### ISSUE THREAD

**Issue by annevk** [jakearchibald/background-fetch#7]
Use `FrozenArray<>`.

**Comment by jakearchibald** [comment]
Just for my own learnings, when would I use sequence rather than `FrozenArray`?

**Comment by annevk** [comment]
Whenever you'd return a new array each time (from a method call) or wherever you want to accept a sequence as argument.

**Comment by annevk** [comment]
We should totally clean up IDL around this I think, along with some of its other syntax, but there hasn't been much bandwidth for that kind of thing thus far.
