### ISSUE TITLE
What if you drain a request?

### ISSUE THREAD

**Issue by annevk** [jakearchibald/background-fetch#9]
Since you give access to the `Request` object, what if someone drains it? Or is it a clone of sorts? Wouldn't that be rather wasteful?

**Comment by jakearchibald** [comment]
My feeling is that `.register` would resolve once all requests had been fully consumed, as the document can't close until the browser has the ability to make the request without the document.

If you're uploading a 200mb video from disk, this may involve copying the video, which isn't great for low-end devices. However, a compatible implementation could hold a write lock on the file and avoid the copying.

I guess the wasteful bit is having to keep that copy around for the "complete" event.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/background-fetch/commit/52bf7437807d2b540697d35f7f5002c09543315d

**Comment by annevk** [comment]
I guess you're basically asking me to review the thing again? It's very much unclear how the specific thing I commented on changed.

**Comment by jakearchibald** [comment]
Headlines:

* `backgroundFetch.fetch` resolves once all requests, including their bodies have been fully read into storage - this counts against quota.
* These requests, and their responses, are stored & count against quota until the `backgroundfetched`, `backgroundfetcherror`, or `backgroundfetchabort` event fires.
* The requests & potentially responses will still be accessible from these events, but transferring them to another storage shouldn't double the quota. As in, when these copies are drained, they're no longer accessible.

Relevant bits from the new explainer:

# API Design

## Starting a background fetch

```js
const registration = await navigator.serviceWorker.ready;
const bgFetchJob = await registration.backgroundFetch.fetch(tag, requests, options);
```

`backgroundFetch.fetch` will reject if:

* …
* The browser fails to store the requests and their bodies.
* …

# Quota usage

The request and response objects will use origin quota until the `backgroundfetched` event.

A requirement is to avoid doubling quota usage when transferring background-fetched items into the cache:

```js
addEventListener('backgroundfetched', event => {
  event.waitUntil(async function() {
    const cache = await caches.open('my-cache');
    const promises = event.fetches.map(({request, response}) => {
      if (response && response.ok) {
        return cache.put(request, response);
      }
    });

    await Promise.all(promises);
  }());
});
```

A user agent could implement this efficiently using streams. Given a response body can only be read once, it can drain it from background fetch storage, whilst feeding it into the cache.

# Example - Uploading a video in the background

```js
// in the page:
form.addEventListener('submit', async event => {
  event.preventDefault();
  const body = new FormData(form);
  const videoName = body.get('video').name;
  const tag = 'video-upload-' + videoName;
  const request = new Request('/upload-video', { body, method: 'POST' });

  const reg = await navigator.serviceWorker.ready;

  try {
    await reg.backgroundFetch.fetch(tag, request, {
      title: "Uploading video"
    });
  }
  catch () {
    // Failed, try and upload from the page.
    // First store the video in IDB in case the user closes the tab
    await storeInIDB(body);
    const response = await fetch('/upload-video', { body, method: 'POST' });
    if (response.ok) showUploadAsComplete();
  }
});
```

```js
// in the service worker:
addEventListener('backgroundfetched', event => {
  if (event.tag.startsWith('video-upload-')) {
    event.updateUI("Video uploaded!");
  }
});

addEventListener('backgroundfetcherror', event => {
  if (event.tag.startsWith('video-upload-')) {
    event.updateUI("Upload failed");

    // Store the data in IDB so it isn't lost:
    event.waitUntil(async function() {
      const formData = await event.fetches[0].request.formData();
      await storeInIDB(formData);
    }());
  }
});
```
